# -*- coding: utf-8 -*-
"""ml-lab-01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a6C6oDVCtNsKzijwJvRiQkCv9NEF-eIs
"""

from sklearn.datasets import load_iris
import pandas as pd

from sklearn.datasets import load_iris
import pandas as pd

# Load the iris dataset
iris = load_iris()

# Create DataFrame with feature data
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Add target column (species)
df['species'] = iris.target

# Display first 5 rows
df.head()

df.shape

df.columns
df.info()

df.describe()

df['species'].value_counts()

import matplotlib.pyplot as plt

plt.scatter(df['sepal length (cm)'], df['petal length (cm)'])
plt.xlabel("Sepal Length")
plt.ylabel("Petal Length")
plt.show()

df[df['species'] == 0].head()
df[df['species'] == 1].head()

df.corr()

df.sort_values(by='petal length (cm)').head()